---
# defaults file for install_jenkins
 tomcat_srv_path: /opt/tomcat
 side_mode_file_path: /home/ubuntu/devops/ansible/side_mode.txt
 jenkins_token_path: /home/ubuntu/devops/ansible/pipeline_token.txt
 jenkins_url : http://mirrors.jenkins.io/war/2.232/jenkins.war
 jenkins_home: /home/tomcat/jenkins_home
 jenkins_username: user
 jenkins_password: password1
 jenkins_server_url: "http://{{ groups['ci_cd_server'][0] }}:8080/jenkins"
 job_name: main
 side_mode: single
