---
# defaults file for install_jenkins
   jenkins_url : http://mirrors.jenkins.io/war/latest/jenkins.war
   jenkins_home: /home/jenkins
   tomcat_home: /opt/tomcat
   jenkins_username: user
   jenkins_password: password1