---
  - name: Add tomcat group
    group:
      name: tomcat

  - name: Add tomcat user
    user:
      name: tomcat
      group: tomcat
      home: "{{tomcat_home}}"
      createhome: no
      system: yes

  - name: Create docker group
    group:
      name: "docker"
      state: present

  - name: Adding user tomcat to docker group
    user:
     name: tomcat
     groups: "docker"
     append: "yes"
    notify: test

  - name: add info to log file
    lineinfile:
     dest: "{{docker_logs_path}}logs.txt"
     line: "user created {{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }} ci_cd_server"
     state: present
     insertafter: EOF
     create: True