---

- name: "add {{action}} on {{where}} to log file"
  lineinfile:
   dest: "{{docker_logs_path}}"
   line: "{{action}} {{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}  {{where}}"
   state: present
   insertafter: EOF
   create: True