---
# handlers file for mysql
 - name: restart mysql
   become: yes
   systemd:
    state: restarted
    daemon_reload: yes
    name: mysql
 - name: test
   become: yes
  # hosts: ci_cd_server
   tasks:
   - name: log
     debug:
      msg: "test"