---
  - name: Install  packages #root
    become: yes
    become_user: root
    apt:
      update_cache: yes
      name: "{{ item }}"
      state: present
    with_items:
      - wget
      - python3-pip
      - openjdk-8-jdk

  - name: Change file ownership, group and permissions #root
    become: yes
    become_user: root
    file:
     path: "{{ tomcat_srv_path }}"
     state: directory
     mode: '0755'
     owner: tomcat
     group: tomcat

  - name: Download Tomcat 
    get_url:
      url: "{{ tomcat_url }}"
      dest : "{{ tomcat_dir }}" 
      owner: tomcat
      group: tomcat

  - name: Extract tomcat archive
    become: yes
    become_user: tomcat
    unarchive:
      src: "{{ tomcat_dir }}"
      dest: "{{ tomcat_srv_path }}" 
      owner: tomcat
      group: tomcat
      remote_src: yes
      extra_opts: "--strip-components=1"
      creates: "{{tomcat_srv_path}}/bin"

  - name: add info to log file
    lineinfile:
     dest: "{{docker_logs_path}}logs.txt"
     line: "install_tomcat {{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }} Jenkins_Server"
     state: present
     insertafter: EOF
     create: True