---
    - name: mysql install
      become: yes
      apt:
       name: mysql-server 
       state: latest
       update_cache: yes
    - name: Check that wp core download exists
      stat:
       path: "{{wp_path}}wp-config-sample.php"
      register: stat_result
    - name: download core
      become: yes
      shell:
       cmd: "wp core download --allow-root"
       chdir: "{{wp_path}}"
      when: stat_result.stat.exists == False 
    - name: Check that wp core configured exists
      stat:
       path: "{{wp_path}}wp-config.php"
      register: stat_result
    - name: check if isset conf file
      become: yes
      shell:
       cmd: "wp core config --dbhost={{wp_db_host}} --dbname={{wp_db_name}} --dbuser={{wp_db_user}} --dbpass={{wp_db_password}}  --allow-root"
       chdir: "{{wp_path}}"
      when: stat_result.stat.exists == False 
    - name: if wp db installed
      command: "mysql --user={{wp_db_user}} --password={{wp_db_password}}  --database={{wp_db_name}}
                --host={{wp_db_host}} --batch --skip-column-names
                --execute='show tables from {{wp_db_name}};'"
      register: stuff
    - name: install wp
      become: yes
      shell:
       cmd: "wp core install --url=http://{{web_server_host}}/ --title=WordPress --admin_user={{wp_username}} --admin_password={{wp_password}} --admin_email={{wp_email}}  --allow-root"
       chdir: "{{wp_path}}"
      when: stuff.stdout_lines|length == 0