---
    - name: mysql install
      become: yes
      apt:
       name: mysql-server 
       state: latest
       update_cache: yes
    - name: Check that wp core download exists
      stat:
       path: "{{wp_path}}wp-config-sample.php"
      register: stat_result
    - name: download core
      become: yes
      shell:
       cmd: "wp core download --allow-root"
       chdir: "{{wp_path}}"
      when: stat_result.stat.exists == False
    - name: rr
      debug:
       var: "{{groups['db_server_host']}}"
    - name: Check that wp core configured exists
      stat:
       path: "{{wp_path}}wp-config.php"
      register: stat_result
    - name: conf wp 1
      block:
      - name: check if isset conf file
        become: yes
        shell:
         cmd: "wp core config --dbhost={{wp_db_host}} --dbname={{wp_db_name}} --dbuser={{wp_db_user}} --dbpass={{wp_db_password}}  --allow-root"
         chdir: "{{wp_path}}"
        when: stat_result.stat.exists == False 
      - name: if wp db installed
        command: "mysql --user={{wp_db_user}} --password={{wp_db_password}}  --database={{wp_db_name}}
                  --host={{wp_db_host}} --batch --skip-column-names
                  --execute='show tables from {{wp_db_name}};'"
        register: stuff
      - name: install wp
        become: yes
        shell:
         cmd: "wp core install --url=http://{{web_server_host_1}}/ --title=WordPress --admin_user={{wp_username}} --admin_password={{wp_password}} --admin_email={{wp_email}}  --allow-root"
         chdir: "{{wp_path}}"
        when: stuff.stdout_lines|length == 0
      when: "'wordpress_server_1' in group_names"


    - name: conf wp 2
      block:
      - name: check if isset conf file
        become: yes
        shell:
         cmd: "wp core config --dbhost={{wp_db_host}} --dbname={{wp_db_name}} --dbuser={{wp_db_user}} --dbpass={{wp_db_password}}  --allow-root"
         chdir: "{{wp_path}}"
        when: stat_result.stat.exists == False 
      - name: if wp db installed
        command: "mysql --user={{wp_db_user}} --password={{wp_db_password}}  --database={{wp_db_name}}
                  --host={{wp_db_host}} --batch --skip-column-names
                  --execute='show tables from {{wp_db_name}};'"
        register: stuff
      - name: install wp
        become: yes
        shell:
         cmd: "wp core install --url=http://{{web_server_host_2}}/ --title=WordPress --admin_user={{wp_username}} --admin_password={{wp_password}} --admin_email={{wp_email}}  --allow-root"
         chdir: "{{wp_path}}"
        when: stuff.stdout_lines|length == 0
      when: "'wordpress_server_2'  in group_names"