---
  - name: Check that the wpcli exists
    stat:
      path: "{{wp_cli_path}}"
    register: stat_result
  - name: download wpcli
    become: yes
    get_url: 
     url: "{{wp_cli_url_download}}"
     dest: "{{wp_cli_path}}"
     mode: "u+x"
    when: stat_result.stat.exists == False 
