---
 - name: download cli
   get_url:
    url: "http://localhost:8080/jenkins/jnlpJars/jenkins-cli.jar"
    dest: /home/jenkins
 - name: avalible registration
   become: yes
   lineinfile:
    dest: '/home/jenkins/config.xml'
    regexp: "hudson.security.SecurityRealm+"
    line: "<securityRealm class=\"hudson.security.HudsonPrivateSecurityRealm\">\n<disableSignup>false</disableSignup>\n
    <enableCaptcha>false</enableCaptcha>\n</securityRealm>"
 - name: restart jenkins
   command:
    cmd: "java -jar jenkins-cli.jar -s http://localhost:8080/jenkins safe-restart"
    chdir: "/home/jenkins"
 - name: wait for jenkins start
   uri:
    url: "http://localhost:8080/jenkins/login"
    follow_redirects: all
    method: GET
   register: _result
   until: _result.status == 200
   retries: 100
   delay: 5
 - name: create user
   shell:
    cmd: >
      echo 'jenkins.model.Jenkins.instance.securityRealm.createAccount("user5", "password123")' | java -jar jenkins-cli.jar -s http://localhost:8080/jenkins groovy =
    chdir: "/home/jenkins"
 - name: avalible registration
   become: yes
   lineinfile:
    dest: '/home/jenkins/config.xml'
    regexp: "hudson.security.AuthorizationStrategy+"
    line: "<authorizationStrategy class=\"hudson.security.FullControlOnceLoggedInAuthorizationStrategy\">\n<denyAnonymousReadAccess>true</denyAnonymousReadAccess>\n</authorizationStrategy>"
 - name:
   become: yes
   lineinfile:
    dest: '/home/jenkins/config.xml'
    regexp: 'disableSignup+'
    line: '<disableSignup>true</disableSignup>'
 - name: restart jenkins
   command:
    cmd: "java -jar jenkins-cli.jar -auth user5:password123 -s http://localhost:8080/jenkins safe-restart"
    chdir: "/home/jenkins"
 - name: wait for jenkins start
   uri:
    url: "http://localhost:8080/jenkins/login"
    follow_redirects: all
    method: GET
   register: _result
   until: _result.status == 200
   retries: 100
   delay: 5
