---
 - name: create jenkins home #root
   become: yes
   become_user: root
   file:
    path: "{{jenkins_home}}"
    state: directory
    mode: '0755'
    owner: tomcat
    group: tomcat
    
 - name: add vars #root
   become: yes
   become_user: root
   block:

   - name: add java opts
     become: yes
     become_user: root
     lineinfile:
      dest: '/etc/environment'
      regexp: '^JAVA_OPTS'
      insertafter: "^JAVA_OPTS=\"-Djenkins.install.runSetupWizard=false\""
      line: "JAVA_OPTS=\"-Djenkins.install.runSetupWizard=false\""
     register: task_result1

   - name: add java opts
     become: yes
     become_user: root
     lineinfile:
      dest: '/etc/environment'
      regexp: '^ANSIBLE_CONFIG'
      insertafter: "^ANSIBLE_CONFIG=\"/home/ubuntu/devops/ansible/ansible.cfg\""
      line: "ANSIBLE_CONFIG=\"/home/ubuntu/devops/ansible/ansible.cfg\""
     register: task_result1

   - name: add java args
     become: yes
     become_user: root
     lineinfile:
      dest: '/etc/environment'
      regexp: '^JAVA_ARGS'
      insertafter: "^JAVA_ARGS=\"-Djenkins.install.runSetupWizard=false\""
      line: "JAVA_ARGS=\"-Djenkins.install.runSetupWizard=false\""
     register: task_result2

   - name: add jenkins home
     become: yes
     become_user: root
     lineinfile:
      dest: '/etc/environment'
      regexp: '^JENKINS_HOME'
      insertafter: "^JENKINS_HOME=\"{{jenkins_home}}\""
      line: "JENKINS_HOME=\"{{jenkins_home}}\""
     register: task_result3

 - name: stop tomcat and restart server
   become: yes
   become_user: tomcat
   block:
   - name: restart server
     become: yes
     become_user: root
     shell: "sleep 5 && reboot"
     async: 1
     poll: 0
   - name: wait for server start
     become: yes
     become_user: root
     wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300

   when: task_result1 is changed or task_result2 is changed or task_result3 is changed

 - name: if jenkins war isset
   stat:
    path: "{{tomcat_srv_path}}/webapps/jenkins.war"
   register: stat_result

 - name: download jenkins
   get_url:
     url: "{{ jenkins_url  }}"
     dest: "{{tomcat_srv_path}}/webapps/"
     mode: '0770'
     owner: tomcat
     group: tomcat
     timeout: 60
   when: not stat_result.stat.exists

 - name: start tomcat
   become: yes
   become_user: tomcat
   shell: "nohup {{tomcat_srv_path}}/bin/startup.sh"

# - name: wait for tomcat start


 - import_playbook: wait_connect.yml
   vars:
    service_url: "http://localhost:8080/"

 - name: wait for jenkins start
   set_fact:
    service_url: "http://localhost:8080/jenkins/"
 - include_playbook: wait_connect.yml

 - name: add info to log file
   lineinfile:
    dest: "{{docker_logs_path}}logs.txt"
    line: "jenkins instaled {{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }} ci_cd_server"
    state: present
    insertafter: EOF
    create: True
