---
#tasks file for install_jenkins
    
   - name: allow access
     become: yes
     lineinfile:
      dest: '/etc/environment'
      regexp: '^JAVA_OPTS'
      insertafter: "^JAVA_OPTS=\"-Djenkins.install.runSetupWizard=false\""
      line: "JAVA_OPTS=\"-Djenkins.install.runSetupWizard=false\""
   - name: allow access
     become: yes
     lineinfile:
      dest: '/etc/environment'
      regexp: '^JAVA_ARGS'
      insertafter: "^JAVA_ARGS=\"-Djenkins.install.runSetupWizard=false\""
      line: "JAVA_ARGS=\"-Djenkins.install.runSetupWizard=false\""
   - name: Reboot immediately if there was a change.
     shell: "sleep 5 && reboot"
     async: 1
     poll: 0
    # when: task_result is changed

   - name: Wait for the reboot to complete if there was a change.
     wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300
   - name: run startup.sh
     become: yes
     command:
      argv:
      - /opt/tomcat/bin/startup.sh
      - sleep 5
      - /opt/tomcat/bin/shutdown.sh
   - name: download jenkins
     get_url:
       url: "{{ jenkins_url  }}"
       dest: /opt/tomcat/webapps/
     register: test
   - name: run startup.sh
     become: yes
     command:
      argv:
      - /opt/tomcat/bin/startup.sh
  #  when: task_result is changed


      # JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
# JAVA_ARGS="-Djenkins.install.runSetupWizard=false"



     # - export JENKINS_HOME=/opt/tomcat/webapps/
  # - name: cofigure jenkins
    # command:
     # argv:
     # - java -Djenkins.install.runSetupWizard=false -jar /opt/tomcat/webapps/jenkins.war
     #chdir: /opt/tomcat/webapps/




