---
#tasks file for install_jenkins

     - name: stop tomcat
       shell: "nohup /opt/tomcat/bin/shutdown.sh"
     - name: add java opts
       become: yes
       lineinfile:
        dest: '/etc/environment'
        regexp: '^JAVA_OPTS'
        insertafter: "^JAVA_OPTS=\"-Djenkins.install.runSetupWizard=false\""
        line: "JAVA_OPTS=\"-Djenkins.install.runSetupWizard=false\""
     - name: add java args
       become: yes
       lineinfile:
        dest: '/etc/environment'
        regexp: '^JAVA_ARGS'
        insertafter: "^JAVA_ARGS=\"-Djenkins.install.runSetupWizard=false\""
        line: "JAVA_ARGS=\"-Djenkins.install.runSetupWizard=false\""
     - name: add jenkins home
       become: yes
       lineinfile:
        dest: '/etc/environment'
        regexp: '^JENKINS_HOME'
        insertafter: "^JENKINS_HOME=\"/home/jenkins\""
        line: "JENKINS_HOME=\"/home/jenkins\""
     - name: Reboot immediately if there was a change.
       shell: "sleep 5 && reboot"
       async: 1
       poll: 0
     - name: Wait for the reboot to complete if there was a change.
       wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
     - name: stop tomcat
       shell: "nohup /opt/tomcat/bin/shutdown.sh"
     - name: wait 5s
       pause:
         seconds: 5
     - name: download jenkins
       get_url:
         url: "{{ jenkins_url  }}"
         dest: /opt/tomcat/webapps/
         mode: '0777'
     - name: stop tomcat
       shell: "nohup /opt/tomcat/bin/startup.sh"
     - name: wait 5s
       pause:
         seconds: 10
     - name: start tomcat
       shell: "nohup /opt/tomcat/bin/shutdown.sh"
     - name: chmod jenkins
       file:
        path: /home/jenkins
        mode: '0777'
        recurse: yes
     - name: chmod jenkins
       file:
        path: /opt/tomcat/webapps/jenkins
        mode: '0777'
        recurse: yes
     - name: start tomcat
       shell: "nohup /opt/tomcat/bin/startup.sh"
#todo сделать удаление переменных системы
#todo попробовать оптимизировать скрипт
#todo вынести переменные и одинаковые куски кода в отедельные части




