---
#tasks file for install_jenkins

     - name: add java opts
       become: yes
       lineinfile:
        dest: '/etc/environment'
        regexp: '^JAVA_OPTS'
        insertafter: "^JAVA_OPTS=\"-Djenkins.install.runSetupWizard=false\""
        line: "JAVA_OPTS=\"-Djenkins.install.runSetupWizard=false\""
     - name: add java args
       become: yes
       lineinfile:
        dest: '/etc/environment'
        regexp: '^JAVA_ARGS'
        insertafter: "^JAVA_ARGS=\"-Djenkins.install.runSetupWizard=false\""
        line: "JAVA_ARGS=\"-Djenkins.install.runSetupWizard=false\""
     - name: add jenkins home
       become: yes
       lineinfile:
        dest: '/etc/environment'
        regexp: '^JENKINS_HOME'
        insertafter: "^JENKINS_HOME=\"/home/jenkins\""
        line: "JENKINS_HOME=\"/home/jenkins\""
     - name: Reboot immediately if there was a change.
       shell: "sleep 5 && reboot"
       async: 1
       poll: 0
     - name: Wait for the reboot to complete if there was a change.
       wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
     - name: download jenkins
       get_url:
         url: "{{ jenkins_url  }}"
         dest: /opt/tomcat/webapps/
         mode: '0777'
     - name: start tomcat
       shell: "nohup /opt/tomcat/bin/startup.sh"
     - name: wait for tomcat start
       uri:
        url: "http://localhost:8080/"
        follow_redirects: safe
        method: GET
       register: _result
       until: _result.status == 200
       retries: 20
       delay: 5
     - name: wait fro jenkins start
       uri:
        url: "http://localhost:8080/jenkins/login"
        follow_redirects: all
        method: GET
       register: _result
       until: _result.status == 200
       retries: 100
       delay: 5
     - include: config_jenkins.yml
#todo сделать удаление переменных системы
#todo попробовать оптимизировать скрипт
#todo вынести переменные и одинаковые куски кода в отедельные части