---
# tasks file for install_jenkins
  - name: download jenkins
    get_url:
      url: "{{ jenkins_url  }}"
      dest: /opt/tomcat/webapps/
    register: test

  - name: run startup.sh
    command:
      argv:
      - /opt/tomcat/bin/startup.sh
      - export JENKINS_HOME=/opt/tomcat/webapps/


