---
  - name: mysql, pip3, python3 install
    become: yes
    become_user: root
    apt:
     name: python3, mysql-server, python3-pip 
     state: latest
     update_cache: yes
    retries: 3
    delay: 3
    register: result
    until: result.rc == 0

  - name: Make sure pymysql is present
    become: yes
    become_user: root
    pip:
     name: pymysql
     state: present
    retries: 3
    delay: 3
    register: result
    until: result.rc == 0