---
# handlers file for install_jenkins

- name: ttt
  become: yes
  become_user: root
  block:
  - name: restart
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0
  - name: wait for start
    wait_for_connection:
     connect_timeout: 20
     sleep: 5
     delay: 5
     timeout: 300

- name: tttt
  uri:
   url: "{{service_url}}"
   follow_redirects: safe
   method: GET
  register: _result
  until: _result.status == 200
  retries: 40
  delay: 5