---
# handlers file for install_jenkins



- name: wait_for_start_service
  uri:
   url: "{{service_url}}"
   follow_redirects: safe
   method: GET
  register: _result
  until: _result.status == 200
  retries: 40
  delay: 5