---
- name: restart jenkins
  command:
    cmd: "java -jar jenkins-cli.jar -auth {{jenkins_username}}:{{jenkins_password}} -s http://localhost:8080/jenkins safe-restart"
    chdir: "{{jenkins_home}}"

- name: wait for jenkins start
  uri:
    url: http://localhost:8080/jenkins/login
    follow_redirects: all
    method: GET
  register: _result
  until: _result.status == 200
  retries: 100
  delay: 5
