---
# tasks file for configure_jenkins

- name: install plugin ansicolor
  jenkins_plugin:
    name: AnsiColor
    url: "{{ url_server }}"
    url_password: admin
    url_username: admin
    state: present

- name: install plugin timestamper
  jenkins_plugin:
    name: timestamper
    url: "{{ url_server }}"
    url_password: admin
    url_username: admin
    state: present

- name: install plugin Pipeline
  jenkins_plugin:
    name: Pipeline
    url: "{{ url_server }}"
    url_password: admin
    url_username: admin
    state: present

- name: make a jenkins test job
  jenkins_job:
    config: "{{ lookup('file', 'templates/test.xml') }}"
    name: test
    password: admin
    url: "{{ url_server }}"
    user: admin
