---
    - name: install nginx
      become: yes
      apt:
        name: nginx 
        state: latest
        update_cache: yes
      retries: 3
      delay: 3
      register: result
      until: result.rc == 0

