---
 - name: Roles config
   hosts: ci_cd_server
   become: yes #todo убрать и расставить правильно где надо
   roles:
   - install_ansible
   - configure_cicd_inst
   - install_tomcat
   - install_jenkins