---
 - name: Roles config
   become: yes #todo убрать и расставить правильно где надо
   hosts: db_server
   roles:
   - mysql

 - name: Roles config
   become: yes #todo убрать и расставить правильно где надо
   hosts: wordpress_server_1, wordpress_server_2
   roles:
   - web-server
   - wordpress 