---
 - name: Roles config
   hosts: ci_cd_server
   vars:
    ansible_ssh_private_key_file: "/home/ubuntu/devops/ansible/keys/key_name_ci_cd_server.pem"
   vars_files: "{{host_vars_path}}"
   become: yes
   become_user: root
   roles:
   - create_user
   - configure_cicd_inst
   - install_docker
   - install_ansible

 - name: Roles config
   hosts: ci_cd_server
   vars:
    ansible_ssh_private_key_file: "/home/ubuntu/devops/ansible/keys/key_name_ci_cd_server.pem"
   vars_files: "{{host_vars_path}}"
   become: yes 
   become_user: tomcat
   roles:
   - install_tomcat
   - install_jenkins
