---
 - name: Roles config
   hosts: ci_cd_server
   become: yes
   become_user: root
   roles:

   - create_user
   - configure_cicd_inst
   - install_docker
   - install_ansible

 - name: Roles config
   hosts: ci_cd_server
   become: yes #todo убрать и расставить правильно где надо
   become_user: tomcat
   roles:
   - install_tomcat
   - install_jenkins
