---
 - name: Roles config
   hosts: ci_cd_server
   become: yes
   become_user: root
   roles:
   - configure_cicd_inst
   - create_user
   - install_docker

 - name: Roles config
   hosts: ci_cd_server
   become: yes #todo убрать и расставить правильно где надо
   roles:
   - install_tomcat

   - install_ansible
   - install_jenkins
