---
 - name: Roles config
   become: yes #todo убрать и расставить правильно где надо
   become_user: root
   hosts: wordpress_server_1, wordpress_server_2
   roles:
   - web-server

 - import_playbook: pb_make_log.yml
   vars:
    action: install_apache
    where: WordPress_Server_1
   when: ("{{lookup('file', '{{remove_side_file}}')}}"  == 2)
 - import_playbook: pb_make_log.yml
   vars:
    action: install_apache
    where: WordPress_Server_2
   when: ("{{lookup('file', '{{remove_side_file}}')}}"  == 2)
 - import_playbook: pb_make_log.yml
   vars:
    action: install_apache
    where: WordPress_Server
   when: ("{{lookup('file', '{{remove_side_file}}')}}"  == 1)
# - name:
#   debug:
#    msg: "{{lookup('file', '{{remove_side_file}}')}}"