---
 - name: Roles config
   become: yes #todo убрать и расставить правильно где надо
   become_user: root
   hosts: wordpress_server_1, wordpress_server_2
   roles:
   - wordpress
 - import_playbook: pb_make_log.yml
   vars:
    action: install_word_press
    where: WordPress_Server_1
   when: ("{{lookup('file', '{{remove_side_file}}')}}  "== 2)
 - import_playbook: pb_make_log.yml
   vars:
    action: install_word_press
    where: WordPress_Server_2
   when: ("{{lookup('file', '{{remove_side_file}}')}}  "== 2)
 - import_playbook: pb_make_log.yml
   vars:
    action: install_word_press
    where: WordPress_Server
   when: ("{{lookup('file', '{{remove_side_file}}')}}  "== 1)