---
 - name: Roles config
   vars_files: "{{remote_vars_path}}"
   hosts: ci_cd_server
   become: yes
   become_user: tomcat
   roles:
   - make_log

 - import_playbook: pb_make_log.yml
   vars:
    actions: install_monitoring_app
    where:  Jenkins_Server