---
- name: install tomcat
  hosts: server_linux
  become: yes
  become_method: sudo
  roles:
   - install_tomcat

- name: install jenkins
  hosts: server_linux
  become: yes
  become_method: sudo
  roles:
    - install_jenkins

- name: config jenkins
  hosts: server_linux
  become: yes
  become_method: sudo
  roles:
    - configure_jenkins


