---
- name: change php config
  become: yes
  lineinfile:
   dest: "/etc/apache2/mods-enabled/dir.conf"
   regexp: "DirectoryIndex index.html index.cgi index.pl index.php index.xhtml index.htm"
   line: "\tDirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm"
   state: present
  notify: restart apache