---
   - name: install apache + php
     become: yes
     become_user: root
     apt:
      name: "{{programs}}"
      state: latest
      update_cache: yes
     retries: 3
     delay: 3
     register: result
     until: result is not failed
